// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv0d_rPWezTGtjhfIJKcHTyjHLTm3b0lM',
    appId: '1:735363224091:web:436eb1538945eab69f9ebe',
    messagingSenderId: '735363224091',
    projectId: 'fir-job-portal-poc',
    authDomain: 'fir-job-portal-poc.firebaseapp.com',
    storageBucket: 'fir-job-portal-poc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUG9ou2thgEe5eQwubRqx0tLBtfMcdpz4',
    appId: '1:735363224091:android:5a45ee0d8001e2599f9ebe',
    messagingSenderId: '735363224091',
    projectId: 'fir-job-portal-poc',
    storageBucket: 'fir-job-portal-poc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3tbCOikRzvJwrPcIZU1qu-omVPoE-rDc',
    appId: '1:735363224091:ios:d67869f2759c99ca9f9ebe',
    messagingSenderId: '735363224091',
    projectId: 'fir-job-portal-poc',
    storageBucket: 'fir-job-portal-poc.appspot.com',
    androidClientId: '735363224091-ijdb64u8qa4lqb4us4evch8kf3e05uv2.apps.googleusercontent.com',
    iosClientId: '735363224091-7qnqqi2f0p0mbhpcb0u3hp9ncjr55l6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseJobPortalPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3tbCOikRzvJwrPcIZU1qu-omVPoE-rDc',
    appId: '1:735363224091:ios:d67869f2759c99ca9f9ebe',
    messagingSenderId: '735363224091',
    projectId: 'fir-job-portal-poc',
    storageBucket: 'fir-job-portal-poc.appspot.com',
    androidClientId: '735363224091-ijdb64u8qa4lqb4us4evch8kf3e05uv2.apps.googleusercontent.com',
    iosClientId: '735363224091-7qnqqi2f0p0mbhpcb0u3hp9ncjr55l6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseJobPortalPoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv0d_rPWezTGtjhfIJKcHTyjHLTm3b0lM',
    appId: '1:735363224091:web:0f3cf23779cf4de69f9ebe',
    messagingSenderId: '735363224091',
    projectId: 'fir-job-portal-poc',
    authDomain: 'fir-job-portal-poc.firebaseapp.com',
    storageBucket: 'fir-job-portal-poc.appspot.com',
  );

}